### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by miketweaver** [Shellntel/scripts#4]
I'm trying to deploy this, and run into this error:

```
~$ ./spin-up.py --config spin-up.conf empire -p 443
[*] Connecting to Amazon's EC2
[*] Generating ssh keypairs
[*] Generating Amazon Security Group
[~] Starting instance, please give about 4 minutes for it to fully boot
[====================] 100%
[*] Provisioning Instance
[*] Enabling Root Logon
[*] Updating SSH Keys
[*] Restarting SSH service
[*] Installing dependencies
[*] Even more dependencies
[*] Cloning github repo
[*] Setting STAGING_KEY and Installing Empire
[*] Changing root profile
[*] Starting REST server
[*] Obtaining session id
/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./spin-up.py", line 845, in <module>
    launch_empire()
  File "./spin-up.py", line 462, in launch_empire
    jdata = json.loads(response.content)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Any clues what to do to fix it?

**Comment by shellntel-acct** [comment]
Reproduced the issue on my end. Looks like this might be a bug with Empire 1.6. I've opened an issue with them, will note when fixed.

**Comment by miketweaver** [comment]
No luck? This script is dead in its current state. Maybe we can set the Empire Version so that we can work with an older version of empire, when it was functional?
